# Generated by Django 3.0 on 2021-04-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_auto_20210411_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
